### ISSUE TITLE
Delete is not deleting record

### ISSUE THREAD

**Issue by Uysim** [vuex-orm/plugin-axios#109]
I do 
```js
User.api().delele({
     params: {
        id: 1
      }
})
```
It called to api but it didn't delete in Vuex Orm

Now I work around
```js
User.api().delele({
     params: {
        id: 1
      }
}).then(()=>{
   User.delete(1)
})
```

**Comment by kiaking** [comment]
@Uysim Yes, this is intended at the moment. Please check out "Note on Delete Method" section at the following:
https://vuex-orm.github.io/plugin-axios/guide/usage.html#request

**Comment by Uysim** [comment]
@kiaking Why don't we delete it directly?

**Comment by kiaking** [comment]
Because we there's no mechanism to determine which record to delete, yet. In your case, maybe `{ params: { id: 1 } }` is the record to delete, but the API could be simple as `DELETE /api/tasks` and it might delete task associated with currently logged in user.

Obviously we need good api to handle delete, but it's not there just yet 😓

**Comment by Uysim** [comment]
@kiaking  got it. Make sense. Thank you so much
