### ISSUE TITLE
persistBy: "create" not deleteAll data on relation

### ISSUE THREAD

**Issue by mean-cj** [vuex-orm/plugin-axios#127]
Hello

I found bug with { persistBy: "create" } 
the item relation is not clear or deleteAll() before/after call order.api()

please review this bug from codesanbox
https://codesandbox.io/s/vuex-orm-relation-test-h6xmb?file=/src/App.vue

** item is exists after call order.api() **
 ```
    await Order.api().get("/orders.json", {
      persistBy: "create",
      persistOptions: {
        create: ["merchant_item"]
      }
    });

or

    await Order.api().get("/orders.json", {
      persistBy: "create",
    });
```

I thank when set "persistBy: "create"," or persistOptions 
deleteALl() any data on relations so will be correct

Thank you.

**Comment by cuebit** [comment]
@mean-cj thanks for opening this issue. 

This is expected behaviour, and I wouldn’t consider this a bug. For `create` to have any effect on a model there needs to exist at least one record for the target relation. Since the reproduction example you’ve provided yields no relations in the second call, the normalisation omits the `merchant_item` altogether subsequently not invoking the `create` command. 

In this scenario, you will almost always want to programmatically remove relations before creating parent models because Vuex ORM is unable to make that decision for you.

There was a similar discussion where an option could be made available to purge an entity if there are no records in the corresponding API request but this is something, at least for now, up to the developer to validate and handle.

**Comment by mean-cj** [comment]
thanks for your so much for your suggestion and your code.

what do you think if there are support deleteAll option on persistOptions
for the choice to clear all data relation before call this { persistBy }

**Comment by cuebit** [comment]
> what do you think if there are support deleteAll option on persistOptions for the choice to clear all relation data before call this { persistBy } 

There will be support for this feature in the next iteration of Vuex ORM. For the time being you may have to resort to the more verbose approach.

**Comment by mean-cj** [comment]
Hello @cuebit 

When i return with save() , the promise return only catch 
`return orders.save()`

```
    Order.api().refresh()
        .then(({ response }) => {
          console.log('then')
        })
        .catch(() => {
          console.log('catch')
        })
```

I don't know why

thanks

**Comment by mean-cj** [comment]
I think action only catch because save() return PromiseValue is undefined 

`console.log( orders.save() )`

```
Promise {<pending>}
__proto__: Promise
[[PromiseStatus]]: "resolved"
[[PromiseValue]]: undefined 
```
