### ISSUE TITLE
Ability to extend the Request class (global custom actions?)

### ISSUE THREAD

**Issue by ZachPerkitny** [vuex-orm/plugin-axios#154]
#### Is your feature request related to a problem? Please describe...

I would like to be able to extend the Request class by adding custom methods to retry a request in the background

#### Describe the solution you'd like

Allowed to define actions in the global config

#### Describe alternatives you've considered

An axios interceptor, but then I don't have access to the model used in the request 

I think a good solution would be to allow the user to define mixins or allow users to define `action` in the global config

**Comment by cuebit** [comment]
You can define actions in the [global](https://vuex-orm.github.io/plugin-axios/guide/configurations.html#actions) and [model](https://vuex-orm.github.io/plugin-axios/guide/custom-actions.html) configs.

Extending the `Request` class is not possible because it is as an internal object. However, like any object, you can patch the class as you please, for example:

```js
import axios from 'axios'
import VuexORM from '@vuex-orm/core'
import VuexORMAxios, { Request } from '@vuex-orm/plugin-axios'

Request.prototype.retry = function (...args) {
  // do something
}

VuexORM.use(VuexORMAxios, { axios })
```
