### ISSUE TITLE
Access data in store

### ISSUE THREAD

**Issue by Yorgovan** [vuex-orm/plugin-axios#62]
I am new to vuex-orm and axios plugin and I am trying to get data from api and then access it in vuex store.
Data is successfully fetched from api with this:

``` js
mounted() {
  User.$get({
    query: {
      offset: 0,
      limit: 100
    }
  })
}
```
And then I am trying to access that data from vuex store with:

``` js
computed: {
  users: () => User.all()
}
```

But `this.users` doesnt contain fetched data. Just this:
```
[
  {
    "$id":"_no_key_1",
    "$isUpdating":false,
    "$updateErrors":[],
    "$isDeleting":false,
    "$deleteErrors":[],
    "id":0,
    "first_name":"",
    "last_name":""
  }
]
```

In vue dev tools I can see that it is not pushed in state.
![gnome-shell-screenshot-T6D46Z](https://user-images.githubusercontent.com/33957795/64030187-5d997c80-cb46-11e9-964e-938d60332afc.png)

How can I push it into state?

Thanks

**Comment by pedro-valentim** [comment]
I've recently installed this package on my project and I'm a similar issue. So, the first thing I noticed was the sequence of events from vuex, after the onRequest mutation list (ctrl + 2 @ Vue Devtools) there was an onError mutation with null as payload.

Is this also happening to you? Because I've may have solved It by fixing my entity's class. It had set the wrong pkey so it wont be able to show state's entity data with the real id as object's key.

**Comment by Yorgovan** [comment]
@pedro-valentim thanks but I don't have onError mutation
This is what I get
![gnome-shell-screenshot-CNL07Z](https://user-images.githubusercontent.com/33957795/64851593-01d7f480-d618-11e9-8d69-32d507a11304.png)

**Comment by Yorgovan** [comment]
I found where the issue is (maybe this is what @pedro-valentim thought but I dodn't get it). My json response is like this:
``` json
{
  "users": [
    {
      "id": 1,
      "first_name": "John",
      "last_name": "Doe"
    },
    {
      "id": 2,
      "first_name": "Jane",
      "last_name": "Doe"
    }
  ]
}
```
And axios plugin expects json without main key "users" so I did this in axios config
``` js
onResponse(response) {
  let result = Object.keys(response.data)[0]
  return response.data[result]
}
```
