### ISSUE TITLE
Interceptors

### ISSUE THREAD

**Issue by Akhail** [vuex-orm/plugin-axios#7]
How i can configure a interceptor for example refresh a token?

**Comment by Akhail** [comment]
@nmihaica and how i can use an adapter like https://github.com/ctimmerm/axios-mock-adapter when need pass the axios instance

**Comment by nmihaica** [comment]
I would then stick with plain `axios` and `axios-mock-adapter` packages without `vuex-orm`.

**Comment by geogeorgiev** [comment]
It would be nice to have interceptors for adding a trailing slash as in this example https://github.com/axios/axios/issues/757#issuecomment-291016487

**Comment by kevrousso** [comment]
I agree too. This would be nice, because currently I have other actions on my API that aren't CRUD and I already have the interceptor setup for the calls that pass by vanilla axios.
I wouldn't want to duplicate the logic in my interceptor and also in the custom hooks you defined for axios.

Please allow us to use the interceptor of axios itself!
