### ISSUE TITLE
Migration examples from version < 0.7

### ISSUE THREAD

**Issue by guillaumebriday** [vuex-orm/plugin-axios#74]
Hey!

This new release looks nice !

But I'm confused on how to upgrade my code base from old versions to the new one with the best practices.

For instance, how I'm supposed to migrate this simple code:

```js
      TimeEntry.$create({
        data: {
          description
        }
      })
```

I'm supposed to set the url for every axios call of this model ? I'm not sure

Thanks

**Comment by chindit** [comment]
You can use a custom action in order to keep your URL automatically added.

In your case, you should use

```js
TimeEntry.api().create({
    data: {
        description
    }
})
```

While your Entity should contain

```js
static apiConfig = {
    actions: {
        create: {
            url: '/time-entry',
            method: 'put',
        },
    }
};
```

**Comment by guillaumebriday** [comment]
Ok thank you

To be sure, it means that what it used to be the convention over configuration now need to be written by hand for every models, right?

In the latest version, with barely no code, I could write `User.$fetch()` and the package used the `static entity = 'users'` to find the correct url with preconfigured methods.

Like here: https://github.com/vuex-orm/plugin-axios/tree/v0.5.1#model-config

If I'm correct, I'm not sure to understand this modification in the api and how it can improve our code.

Maybe the new version could keep this old behaviour?

Thank you in advance

**Comment by kiaking** [comment]
> To be sure, it means that what it used to be the convention over configuration now need to be written by hand for every models, right?

Yes, that's correct.

> If I'm correct, I'm not sure to understand this modification in the api and how it can improve our code.

The problem with the latter approach, where the plugin uses the `static entity` value as a URL, was that there are many cases the URL is not like that.

Predefined methods, such as `$fetch` and `$create` was good as long as the model stick to its convention, but when you need to customize them, it caused wired inconsistency on API.

For example, the new Axios plugin lets you call all Axios methods such as `get` and `delete`. It looks like this `User.api().get('/API/users', { ... })`. Now, if you have a preconfigured URL, we have the problem of passing the URL to the argument. Because it has to be something like `User.api().get(undefined, { ... })` or something like this. I didn't want to do this.

I'm thinking of adding back the feature where somehow Axios plugin uses `static entity` as default URL schema, but I just couldn't find out the elegant way to do that.

I do understand your request, and definitely, we should be able to do that!

**Comment by kiaking** [comment]
Closing the issue due to inactivity. We should have another issue for model entity name support if we need that.
