### ISSUE TITLE
get data from api without importing the model

### ISSUE THREAD

**Issue by toinbis** [vuex-orm/plugin-axios#95]
I've been using vuexorm with such syntax `this.$store.getters['entities/user/query']().all()` . I liked the idea of calling the global store, not having to import anything at component level.  

Now I try to use axios plugin. Following the docs, I made this work `import User from '../database/models/User'` <...>  `User.api().get('http://127.0.0.1:8000/api/v1/user/')` . Am wondering if there is a way to use axios plugin with the syntax i'm used to, i.e. is anything like `this.$store.api['entities/users']().get('http://127.0.0.1:8000/api/v1/user/')` possible?  

Thanks a lot!

**Comment by cuebit** [comment]
You absolutely can, perhaps not exactly the way you've described but most certainly achievable since [@vuex-orm/core v0.35](https://github.com/vuex-orm/vuex-orm/releases/tag/v0.35.2)

Vuex ORM v0.35 introduces an additional [means of retrieving models](https://vuex-orm.github.io/vuex-orm/guide/model/retrieving-models.html) without the need to import the model modules directly.

```
this.$store.$db().model('users').api().get('http://127.0.0.1:8000/api/v1/user/')
```

**Comment by toinbis** [comment]
Thanks a lot for guidance!
